version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4SSW0rD
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: lab1
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  sonar:
    image: sonarqube:latest
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    ports:
      - 9000:9000