version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4SSW0rD
      MYSQL_USER: MainUser
      MYSQL_PASSWORD: MainPassword
      MYSQL_DATABASE: lab1
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
