version: "3"
services:

  app:
    build: .
    depends_on:
      - db
      - splunk
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      SPLUNK_TOKEN: 7246f43a-25be-4a9a-afaf-ebe23c5db3b9

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P4SSW0rD
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: lab1
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  splunk:
    image: splunk/splunk
    environment:
      SPLUNK_PASSWORD: SplunkP@ssW0rD!
      SPLUNK_START_ARGS: --accept-license
    ports:
      - "8000:8000"
      - "8088:8088"
